### PR TITLE
don't fill every row with empty cells but only add cells with values

### PR DESCRIPTION
**Pull request by eMBee**
using http://stackoverflow.com/a/4544699/1846474
we can avoid filling every row with 1024 cells, but stop at the last cell that actually has a value.

instead of appending we count the columns, and directly set that column, using GrowingList to fill in the intermediate values.

### CODE REVIEW

**Comment by vazhnov** [comment]
This is interesting idea!

**Comment by eMBee** [comment]
this can probably be extended to rows as well so that each row has the same position as in the spreadsheet.

it might also be worth to add code to (optionally?) make all columns of equal length by finding the longest row, and then adjusting all other rows to match.

**Comment by marcoconti83** [comment]
I like the idea of making all rows of equal length matching the longest one!

**Comment by vazhnov** [comment]
Merging?

**Comment by marcoconti83** [comment]
I will merge this. If anyone wants to pick up the idea of @eMBee of making the column all of equal lengths, it can be done in a new PR.

**Pull request merged**
